# Generated by Django 4.2.7 on 2023-11-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produtos",
            name="slug",
        ),
        migrations.AlterField(
            model_name="produtos",
            name="image",
            field=models.ImageField(upload_to="imgs/produtos"),
        ),
    ]
