# Generated by Django 4.2.7 on 2023-11-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_remove_produtos_slug_alter_produtos_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="image",
            field=models.ImageField(upload_to=" static/imgs/"),
        ),
    ]
